In [1]:
import numpy as np #

# The numpy array

In [2]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a1.ndim

1

In [4]:
a1.shape

(3,)

In [5]:
a2 = np.array([[1,2,3],[3,4,5]])
a2

array([[1, 2, 3],
       [3, 4, 5]])

In [6]:
a2.ndim

2

In [7]:
a2.shape

(2, 3)

In [10]:
a3 = np.array([1,2,3.3])
a3

array([1. , 2. , 3.3])

In [11]:
a3.dtype

dtype('float64')

In [12]:
a3 = np.array([1,2,3.3], dtype=int)
a3

array([1, 2, 3])

In [14]:
a4 = np.array([ ['f','l','a','k','e'],['s','n','a','k','e'],['a','w','a','k','e'] ])

a4.shape

(3, 5)

In [29]:
a4.ndim

2

In [15]:
a4

array([['f', 'l', 'a', 'k', 'e'],
       ['s', 'n', 'a', 'k', 'e'],
       ['a', 'w', 'a', 'k', 'e']], dtype='<U1')

In [16]:
np.arange(0,15)  
#Note that the lower bound argument 0 is included, while the upper bound argument 15 is excluded.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
np.arange(0,15,2) #the start point and the endpoint are included

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [18]:
np.linspace(0,100,3, endpoint=False)  
#We can exclude the endpoint using the parameter endpoint=False as follows:

array([ 0.        , 33.33333333, 66.66666667])

In [21]:
x=np.array(11)
x


array(11)

In [22]:
x.shape

()

In [23]:
x.ndim

0

In [26]:
XX = np.array([[1],[2],[3],[4]])
XX


array([[1],
       [2],
       [3],
       [4]])

In [27]:
XX.shape

(4, 1)

In [28]:
XX.ndim

2

In [31]:
A1 = np.array([1,3])
A1


array([1, 3])

In [34]:
A1.shape



(2,)

In [33]:
A1.ndim

1

In [35]:
A2 = np.array([[1],[3]])
A2



array([[1],
       [3]])

In [36]:
A2.shape


(2, 1)

In [37]:
A2.ndim

2

In [ ]:
np.array([1,'2',3])  #where all items are strings 

* Yes, Numpy uses the most generic type given the array values

import numpy as np

a = np.array([1.23, 2, 3])
print(a.dtype) # float

b = np.array([1.23, '1', 2])
print(b.dtype) # <U32 (Unicode string) see https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.dtypes.html



# Basic operatations with arrays

In [41]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
a.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

It is important to note that the reshape() function returns a new array with the new shape and does not actually change the original array. 

In [44]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

In [48]:
A

array([[1, 1],
       [0, 1]])

In [49]:
B

array([[2, 0],
       [3, 4]])

In [45]:
A*B    #  element wise

array([[2, 0],
       [0, 4]])

In [47]:
A.dot(B)   # matrix multiplication

array([[5, 4],
       [3, 4]])

In [54]:
# x11 = 1*2 + 1*3 = 5
# x12 = 1*0 + 1*4 = 4
# x21 = 0*2 + 1*3 = 3
# x22 = 0*0 + 1*4 = 4

串联数组 Concatenating arrays

In [50]:
a = np.array([11,22])
b = np.array([18,7,6])
c = np.array([1,3,5])
d = np.concatenate((a,b,c))
d

array([11, 22, 18,  7,  6,  1,  3,  5])

In [51]:
a = np.array([[1, 2], [3, 4]])  # two arrays with shape (2,2).
b = np.array([[5, 6], [7, 8]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [52]:
np.concatenate((a, b), axis=1)  # this means gluing the arrays side by side

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# 05 Indexing

In [55]:
a = np.reshape(np.arange(12),(4,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [56]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
a[0,0] # [x,y]     first row and the first column 

0

In [58]:
a[3,0]

9

In [59]:
a[1:3,0]  # x = 1, 2 without 3

array([3, 6])

In [60]:
a[:,2]  # 2 column  : operator selects all the entries

array([ 2,  5,  8, 11])

In [61]:
a[0:4:2,0]

array([0, 6])

* Slicing notation: the notation [i:j:k] selects the entries: i, i+k, i+2k, ..., all the way until the last entry of this form that is smaller than j


* If it is a view, then the data of both the view and the original array are shared. This means that if we modify the view, we modify the original array.
* On the other hand, if the returned objected is a copy then modifying the copy will have no effect on the original array. 

In [62]:
a[0,0] = 5

In [63]:
a

array([[ 5,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

* This is because the slicing operation always returns a view of the array! This will be an important detail to keep in mind. 

In [65]:
b = np.array([[11, 22],[33, 44],[55, 66]])
b

array([[11, 22],
       [33, 44],
       [55, 66]])

In [76]:
b.shape

(3,)

In [67]:
c = b.reshape((b.shape[0], b.shape[1], 1))
c

array([[[11],
        [22]],

       [[33],
        [44]],

       [[55],
        [66]]])

In [77]:
c.shape


(3, 2, 1)

In [68]:
c.shape

(3, 2, 1)

In [69]:

a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
a[1]

200

* This is because the slicing operation always returns a view of the array! This will be an important detail to keep in mind. 

*6. Exercise: slicing arrays

 * Create a one-dimensional array with the numbers from 1 to 36 (included).

In [88]:
AA = np.arange(1,37)
AA

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

* Use the reshape function to transform this into a two-dimensional array with 6 rows and 6 columns.

In [89]:
AA2 = AA.reshape(6,6)
AA2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

*  Obtain a one-dimensional array of shape (6) containing the blue entries.

In [91]:
AA3 = AA2[:,1]
AA3

array([ 2,  8, 14, 20, 26, 32])

* Obtain a two-dimensional array of shape (2,2) containing the yellow entries.

In [98]:
AA4 = AA2[0:2,4:6]
AA4

array([[ 5,  6],
       [11, 12]])

In [99]:
AA4.shape

(2, 2)

*  Obtain a one-dimensional array of shape (2) containing the red entries.

In [104]:
AA5 = AA2[-1, -2:]
AA5

array([35, 36])

In [105]:
AA5.shape

(2,)

* Obtain a two-dimensional array of shape (2,3) containing the green entries.


In [110]:
AA6 = AA2[-4:-1:2, 0:6:2]
AA6

array([[13, 15, 17],
       [25, 27, 29]])

# Slicing

In [112]:
a = np.arange(1,37).reshape(6,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [113]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [114]:
a[:,1]

array([ 2,  8, 14, 20, 26, 32])

In [115]:
a[0:2,4:6]

array([[ 5,  6],
       [11, 12]])

In [116]:
a[5,4:]

array([35, 36])

In [117]:
a[2::2, ::2]

array([[13, 15, 17],
       [25, 27, 29]])

# Boolean masking

In [119]:
a = np.reshape(np.arange(12),(4,3))
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [120]:
a>8

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [121]:
a[a>8] = 0 

In [122]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 0, 0]])

# Broadcasting
Broadcasting rule

 * Take the tuples giving the shape of each array.
 *  If one of the tuples is shorter (because the array has fewer axes) then pad it with 1's from the front until it has the same size as the longer tuple.
 * Now compare the tuples element by element and check whether at each position either (i) the entries are equal, or (ii) one of the entries is 1. If this is true for each position, then broadcasting can occur. Otherwise, broadcasting cannot occur.

In [123]:
a = np.array([1,2,3])
a * 10

array([10, 20, 30])

In [124]:
np.array([ 1,  2,  3]) * np.array([10, 10, 10])

array([10, 20, 30])

In [127]:
a = np.array([[1], [2], [3], [4]])
b = np.array([10, 20, 30])


array([10, 20, 30])

In [128]:
a

array([[1],
       [2],
       [3],
       [4]])

In [129]:
b

array([10, 20, 30])

In [126]:
a + b

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [130]:
a = np.array([[1,2,3],[4,5,6]]) 
b = np.array([[1,2],[8,10],[3,12]]) 

In [131]:
a.shape

(2, 3)

In [132]:
b.shape

(3, 2)

# Exercise: distance to origin

In [137]:
dist_to_origin = [0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391]
dist_to_origin   #  a list

[0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391]

In [136]:
dist = np.array(dist_to_origin)
dist

array([   0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391])

In [140]:
dist_T = dist.reshape(10,1)
dist_T

array([[   0],
       [1498],
       [1063],
       [1968],
       [1498],
       [1758],
       [1469],
       [1472],
       [2230],
       [2391]])

In [141]:
dist_matrix = np.abs(dist - dist_T)

In [142]:
dist_matrix

array([[   0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1063,  435,    0,  905,  435,  695,  406,  409, 1167, 1328],
       [1968,  470,  905,    0,  470,  210,  499,  496,  262,  423],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1758,  260,  695,  210,  260,    0,  289,  286,  472,  633],
       [1469,   29,  406,  499,   29,  289,    0,    3,  761,  922],
       [1472,   26,  409,  496,   26,  286,    3,    0,  758,  919],
       [2230,  732, 1167,  262,  732,  472,  761,  758,    0,  161],
       [2391,  893, 1328,  423,  893,  633,  922,  919,  161,    0]])

# Copies and views   Name binding

In [ ]:
a = np.arange(5)
a
# array([ 0,  1,  2,  3,  4])

In [ ]:
b = a # "a" and "b" are bound to the same array
b[0] = 5
a
# array([ 5,  1,  2,  3,  4])

In [ ]:
a = np.arange(10)
b = a[:2] # "b" is a narrower view of the array
b[0] = 10
a
# array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a = np.arange(10)
b = a.copy()[:2] # "b" is bound to a new array i.e. a copy of "a"
b[0] = 10
a
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a = np.arange(12)
b = a.reshape(3, 4) # reshape() returns a view of the array, but with a new shape
b
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

In [ ]:
b[0] = 10 # changes the underlying data of both "a" and "b"
a
# array([10, 10, 10, 10,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
b
# array([[10, 10, 10, 10],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])